runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT main:app
service: wicker-park

env_variables:
  BUCKET_NAME: "wicker-park-gcs-bucket"
  APP_ENV: "Production"

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /static
  static_dir: static

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
  http_headers:
    Access-Control-Allow-Origin: "*"
